# Generated by Django 5.1.7 on 2025-03-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='Name of the location (e.g., Bangalore, Chennai)', max_length=200)),
                ('address', models.TextField(help_text='Complete location address')),
                ('company_gst', models.CharField(help_text='GST number specific to this location (15 characters)', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when location was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when location details were last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if location is currently active')),
            ],
            options={
                'verbose_name': 'Vendor Location',
                'verbose_name_plural': 'Vendor Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=200, unique=True)),
                ('company_pan_card', models.CharField(help_text='Company PAN Card number (10 characters)', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when vendor was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when vendor details were last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if vendor is currently active')),
            ],
            options={
                'verbose_name': 'Vendor Registration',
                'verbose_name_plural': 'Vendor Registrations',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='LocationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(help_text='Name of the contact person', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when contact was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when contact details were last updated')),
                ('location', models.ForeignKey(help_text='Location to which this contact belongs', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='employee.vendorlocation')),
            ],
            options={
                'verbose_name': 'Location Contact',
                'verbose_name_plural': 'Location Contacts',
                'ordering': ['contact_person'],
            },
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor to which this location belongs', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='employee.vendorregistration'),
        ),
    ]
