# Generated by Django 5.1.7 on 2025-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontact',
            name='Position',
            field=models.CharField(default=1, help_text='Job Profile Name (e.g: HPD , PDH)', max_length=30),
            preserve_default=False,
        ),
    ]
