# Generated by Django 5.1.7 on 2025-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlocation',
            name='company_gst',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AddConstraint(
            model_name='vendorlocation',
            constraint=models.UniqueConstraint(
                fields=('vendor', 'company_gst'), 
                name='unique_gst_per_vendor'
            ),
        ),
        
    ]
