# Generated by Django 5.1.7 on 2025-03-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_vendorlocation_unique_gst_across_vendors_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorlocation',
            name='unique_gst_across_vendors',
        ),
    ]
