# Generated by Django 5.1.7 on 2025-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_vendorlocation_unique_gst_across_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlocation',
            name='company_gst',
            field=models.CharField(help_text='GST number specific to this location (15 characters)', max_length=15),
        ),
    ]
