# Generated by Django 5.1.7 on 2025-03-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_vendorlocation_company_gst'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorlocation',
            name='unique_gst_per_vendor',
        ),
        migrations.AlterField(
            model_name='vendorlocation',
            name='company_gst',
            field=models.CharField(help_text='GST number specific to this location (15 characters)', max_length=15, unique=True),
        ),
    ]
