# Generated by Django 5.1.7 on 2025-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_vendorlocation_company_gst'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorlocation',
            constraint=models.UniqueConstraint(fields=('company_gst', 'vendor'), name='unique_gst_vendor_pair'),
        ),
    ]
