# Generated by Django 5.1.7 on 2025-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_vendorlocation_unique_gst_vendor_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorlocation',
            name='unique_gst_vendor_pair',
        ),
        migrations.AlterField(
            model_name='vendorlocation',
            name='company_gst',
            field=models.CharField(help_text='GST number specific to this location (15-30 characters)', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='vendorlocation',
            unique_together={('vendor', 'company_gst')},
        ),
    ]
