# Generated by Django 5.1.7 on 2025-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='current_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='permanent_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
