# Generated by Django 5.1.7 on 2025-03-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_employeeprofile_current_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='work_location',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='WorkLocation',
        ),
    ]
