# Generated by Django 5.1.7 on 2025-03-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter You Name', max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('work_location', models.CharField(max_length=255)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('Manager', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_account', models.CharField(max_length=50)),
                ('personal_id', models.CharField(max_length=50, unique=True)),
                ('education', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_method', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Other')], default='EMAIL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='Name of the location (e.g., Bangalore, Chennai)', max_length=200)),
                ('address', models.TextField(help_text='Complete location address')),
                ('company_gst', models.CharField(help_text='GST number specific to this location (15 characters)', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when location was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when location details were last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if location is currently active')),
            ],
            options={
                'verbose_name': 'Vendor Location',
                'verbose_name_plural': 'Vendor Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=200, unique=True)),
                ('company_pan_card', models.CharField(help_text='Company PAN Card number (10 characters)', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when vendor was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when vendor details were last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if vendor is currently active')),
            ],
            options={
                'verbose_name': 'Vendor Registration',
                'verbose_name_plural': 'Vendor Registrations',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_details', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='procurement.vendorlocation'),
        ),
        migrations.CreateModel(
            name='LocationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(help_text='Name of the contact person', max_length=100)),
                ('Position', models.CharField(help_text='Job Profile Name (e.g: HPD , PDH)', max_length=30)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when contact was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when contact details were last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if vendor is currently active')),
                ('location', models.ForeignKey(help_text='Location to which this contact belongs', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='procurement.vendorlocation')),
            ],
            options={
                'verbose_name': 'Location Contact',
                'verbose_name_plural': 'Location Contacts',
                'ordering': ['contact_person'],
            },
        ),
        migrations.AddField(
            model_name='vendorlocation',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor to which this location belongs', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='procurement.vendorregistration'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.vendorregistration'),
        ),
    ]
