# Generated by Django 5.1.7 on 2025-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlocation',
            name='company_gst',
            field=models.CharField(help_text='GST number specific to this location (15 characters)', max_length=15),
        ),
    ]
